### ISSUE TITLE
Package Status -- Support ES6 (Babel)

### ISSUE THREAD

**Issue by mikeerickson** [boogie666/atom-mocha#11]
Is this package still be supported?  It would be nice to support ES6 (Babel Compiler)

This ticket https://github.com/boogie666/atom-mocha/issues/6 has all the details

If it is not supported, I would be happy to help

**Comment by boogie666** [comment]
Hi, support for this is spotty, i don't have that much time to work on it as much. 

It does support ES6, in fact it should be the default. It does use Babel 5 though. I tried to add Babel 6 but the inline compilation is quite slow, not sure what happened there with babel.
