### ISSUE TITLE
Clicking a file-name in the errors pane opens the file in a wrong path

### ISSUE THREAD

**Issue by erelsgl** [boogie666/atom-mocha#12]
Here is what I did:
1. Opened in Atom the folder "/home/erelsgl/git/computational-geometry"
2. In Atom tree-view, I opened the test folder, Right-clicked a file "data-test.js" and selected "Run Test"
3. There was an error in the test. The last line in the error message said that it is "at Context.<anonymous> (git/computational-geometry/test/data-test.js:144:52). I clicked this line.
4. As a result, a new, empty file opened in the Atom editor.   The full path to that file is:
   
     /home/erelsgl/git/computational-geometry/git/computational-geometry/test/data-test.js

Apparently, atom-mocha has some difficulty in calculating the correct path to the test file. It should have opened the file:

```
/home/erelsgl/git/computational-geometry/test/data-test.js
```

**Comment by boogie666** [comment]
Thanks for using atom-mocha and submitting issues :)

I'm pretty sure this is fixed with 0.0.9. I'm gonna close this issue, but please feel free to reopen it if it's still a problem.

Cheers,
Boogie
