### ISSUE TITLE
Closing the test-results pane

### ISSUE THREAD

**Issue by erelsgl** [boogie666/atom-mocha#14]
How can I close the test results pane?

Currently, I can close it only by closing Atom  or by disabling atom-mocha... both of which are not very good ways.

**Comment by boogie666** [comment]
By default Alt + Ctrl + T toggles the show/hide on the test result pane.

Alternatively (if you have that bound to something else) the Packages > atom-mocha > Show/Hide Test Panel menu entry will do the same thing.

the action for toggling the pane is atom-mocha:toggle, you can bind to other keys as you see fit.

Hope this help,
Cheers.

**Comment by erelsgl** [comment]
OK! Maybe it should be added to the readme.
