### ISSUE TITLE
Error : EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by JoshuaBWT** [boogie666/atom-mocha#15]
Hi,

I'm using atom on Windows 10 and when I try to run any test which has a console output (console.log or even a test assertion error), I get an **EPERM** error thrown. 

When the test has no errors everything runs fine.

I tried to run Atom as an administrator and it didn't change anything.

My config is the following :
**atom** : 1.11.2
**node** : 6.9.1
**npm** : 3.10.8
**mocha** : 3.1.2.

And here is the screenshot of the error I get :

![image](https://cloud.githubusercontent.com/assets/14292455/19939752/8476536c-a12a-11e6-96e5-dac1fb25bdf8.png)

**Comment by boogie666** [comment]
Hi should be fixed. In case you still using atom mocha :) can you please install the lastest version and give this a shot? if it does not work please reopen this issue
