### ISSUE TITLE
no output when a 'before' or 'beforeEach' block throws

### ISSUE THREAD

**Issue by whatwapp** [boogie666/atom-mocha#18]
Hi,
when writing tests, if a 'before' or 'beforeEach' block throws an error, the test results panel show each test greyed out (because they were not executed) and there is no indication of what went wrong. mocha itself (ran from terminal) reports the error like
```
1) <test suite> "before each" hook for "<test>":
     TypeError: Cannot read property 'returns' of undefined
      at Context.<anonymous> (***.js:21:36)
```
but it does not gets reported in atom.

**Comment by boogie666** [comment]
I've added hooks :) please update atom-mocha :)
